### ISSUE TITLE
Skeleton

### ISSUE THREAD

**Issue by MarcinMikolaj** [MarcinMikolaj/note-box#4]
### 1. Provide Model
- [x] Note model
```
{
“title”:String,
“content”:String
“date”:LocalDateTime
}
```

### 3. Provide API.

Available endpoints:
- [x] Add new note.
- [x] Remove existing note.
- [x] Update existing note.
- [x] Find note by title (any string of characters that is included in title)
- [x] Find all notes.

### 4. Provide validation for model.

Constraints:
- [x] “title”:String[A-Za-z],
- [x] “content”:String[A-Za-z0-9\s]
